import { Optional } from "sequelize";

// Enums
export enum UserRole {
  ADMIN = "admin",
  USER = "user",
  TRADER = "trader",
}

// User attributes interface
export interface UserAttributes {
  id: number;
  email: string;
  username: string;
  password: string;
  role: UserRole;
  wallet_address?: string;
  balance: number;

  // Add timestamp fields - managed by Sequelize but needed for TypeScript
  created_at: Date;
  updated_at: Date;
  deleted_at?: Date | null;

  //   Will be added later
  //   email_verified: boolean;
  //   email_verification_token?: string;
  //   email_verified_at?: Date;
  //   password_reset_token?: string;
  //   password_reset_expires?: Date;
}

// Optional fields for creation - timestamps are auto-generated by Sequelize
export interface UserCreationAttributes
  extends Optional<
    UserAttributes,
    "id" | "role" | "balance" | "created_at" | "updated_at" | "deleted_at"
  > {}
